version: '3.8'
services:
  currency-exchange:
    image: miguelisaza95/currency-exchange
    ports:
      - "8000:8000"
    restart: always
    networks:
      - currency-network

  currency-conversion:
    image: miguelisaza95/currency-conversion
    ports:
      - "8100:8100"
    restart: always
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange
    networks:
      - currency-network
  
# Networks to be created to facilitate communication between containers
networks:
  currency-network:
          # use bridge drive by default
